In [3]:
import datetime
import pandas as pd
import numpy as np

# Misal skema dataset-nya seperti berikut: => Silahkan dimodifikasi sesuai case Anda
kolomFitur_X = ['Gender (X1)','Daerah Asal (X2)', 'Kategori Barang (X3)', 'Umur (X4)', 'Nilai Transaksi dalam KRp (X5)', 'Rating Barang (X6)']

# Interval atau Variasi nilai fitur
nilaiFitur_Gender = ['Pria','Wanita']
nilaiFitur_Daerah_Asal = ['Sumatera Utara','Sumatera Barat','Jawa Barat', 'DKI Jakarta', 'Jawa Tengah', 'Jawa Timur', 'D.I. Yogyakarta', 'Bali', 'Kalimantan Timur']
nilaiFitur_Kategori_Barang = ['Elektronik', 'Fashion', 'FnB', 'Kecantikan', 'Kesehatan', 'Alat Musik', 'Perhiasan']
nilaiFitur_Umur = [15,60]
nilaiFitur_Nilai_Transaksi_dalam_KRp = [10,30000]
nilaiFitur_Rating_Barang = [1,5]

# set bykData = 3*np.power(10,7)
bykData = np.power(10,7)
bykFitur = len(kolomFitur_X)-1

print('Banyak Data = ', bykData)
print('Banyak Fitur = ', bykFitur)

# generate isi dataset
content_dataGenerate = np.array([np.arange(bykData)]*(bykFitur+1)).T
df_gen = pd.DataFrame(content_dataGenerate, columns=kolomFitur_X)

# set secara random nilai Fitur untuk generate data
df_gen ['Gender (X1)'] = np.random.choice(nilaiFitur_Gender, df_gen.shape[0])
df_gen ['Daerah Asal (X2)'] = np.random.choice(nilaiFitur_Daerah_Asal, df_gen.shape[0])
df_gen ['Kategori Barang (X3)'] = np.random.choice(nilaiFitur_Kategori_Barang, df_gen.shape[0])
df_gen ['Umur (X4)'] = np.random.randint(nilaiFitur_Umur[0], nilaiFitur_Umur[1], df_gen.shape[0])
df_gen ['Nilai Transaksi dalam KRp (X5)'] = np.random.randint(nilaiFitur_Nilai_Transaksi_dalam_KRp[0], nilaiFitur_Nilai_Transaksi_dalam_KRp[1], df_gen.shape[0])
df_gen ['Rating Barang (X6)'] = np.random.randint(nilaiFitur_Rating_Barang[0], nilaiFitur_Rating_Barang[1], df_gen.shape[0])

# save dataframe generate ke *.csv
file_name_data_generate = 'Data_Generate_Cluster_Segmen_Ecommerce.csv'
df_gen.to_csv(file_name_data_generate, encoding='utf-8', index=False)

# read file *.csv dan tampilkan
data_generate = pd.read_csv(file_name_data_generate)

# Menampilkan data
print('\nMenampilkan hasil generate dataset:')
display(data_generate)

Banyak Data =  10000000
Banyak Fitur =  5

Menampilkan hasil generate dataset:

        Gender (X1)  ... Rating Barang (X6)
0            Wanita  ...                  3
1            Wanita  ...                  2
2              Pria  ...                  2
3            Wanita  ...                  2
4            Wanita  ...                  2
...             ...  ...                ...
9999995        Pria  ...                  2
9999996      Wanita  ...                  4
9999997      Wanita  ...                  4
9999998      Wanita  ...                  4
9999999        Pria  ...                  1

[10000000 rows x 6 columns]

Link file csv: https://bit.ly/data_generate_10juta